// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include <memory>

namespace nativium { namespace net { namespace http {

class HttpServer {
public:
    virtual ~HttpServer() = default;

    static /*not-null*/ std::shared_ptr<HttpServer> shared();

    virtual void initialize() = 0;

    virtual void start() = 0;
};

} } }  // namespace nativium::net::http
