// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import <Foundation/Foundation.h>
@class NTVHttpServer;


@interface NTVHttpServer : NSObject

+ (nullable NTVHttpServer *)shared;

- (void)initialize;

- (void)start;

@end
