// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni


export interface HttpServer {
    initialize(): void;
    start(): void;
}
export interface HttpServer_statics {
    shared(): HttpServer;
}

export interface HttpServer_statics {
    HttpServer: HttpServer_statics;
}
