// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/wasm/djinni_wasm.hpp"
#include "nativium/net/http/HttpServer.hpp"

namespace djinni_generated {

struct NTVHttpServer : ::djinni::JsInterface<::nativium::net::http::HttpServer, NTVHttpServer> {
    using CppType = std::shared_ptr<::nativium::net::http::HttpServer>;
    using CppOptType = std::shared_ptr<::nativium::net::http::HttpServer>;
    using JsType = em::val;
    using Boxed = NTVHttpServer;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) {
        djinni::checkForNull(c.get(), "NTVHttpServer::fromCpp");
        return fromCppOpt(c);
    }

    static em::val cppProxyMethods();

    static em::val shared();
    static void initialize(const CppType& self);
    static void start(const CppType& self);

};

}  // namespace djinni_generated
