// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "com/nativium/net/http/NTVHttpServer.hpp"  // my header

namespace djinni_generated {

NTVHttpServer::NTVHttpServer() : ::djinni::JniInterface<::nativium::net::http::HttpServer, NTVHttpServer>("com/nativium/net/http/HttpServer$CppProxy") {}

NTVHttpServer::~NTVHttpServer() = default;


CJNIEXPORT void JNICALL Java_com_nativium_net_http_HttpServer_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        delete reinterpret_cast<::djinni::CppProxyHandle<::nativium::net::http::HttpServer>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_nativium_net_http_HttpServer_shared(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        auto r = ::nativium::net::http::HttpServer::shared();
        return ::djinni::release(::djinni_generated::NTVHttpServer::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_nativium_net_http_HttpServer_00024CppProxy_native_1initialize(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::nativium::net::http::HttpServer>(nativeRef);
        ref->initialize();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_nativium_net_http_HttpServer_00024CppProxy_native_1start(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::nativium::net::http::HttpServer>(nativeRef);
        ref->start();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
